version: 2.1
jobs:
  compile:
   docker:
      - image: z4nyx/docker:latest
   steps:
      - run:
          command: |
           git config --global user.name "dustxyz"
           git config --global user.email "dustxyz@criptext.com"
           git config --global color.ui false
           git clone https://github.com/flaahokiller/circleci-aosp
           cd circleci-aosp
           bash .circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile

