version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:latest
   steps:
      - run:
          command: |
           git config --global user.name "flashokiller"
           git config --global user.email "flashokiller@gmail.com"
           git config --global color.ui true
           git clone https://github.com/flashokiller/circleci-aosp
           cd circleci-aosp
           bash .circleci/build.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile

